name: client_deployment_app
description: A Flutter application to automate the client deployment process.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Utilities
  equatable: ^2.0.5
  get_it: ^7.6.7
  go_router: ^13.2.0
  intl: ^0.19.0

  # State Management
  flutter_bloc: ^8.1.4

  # Networking
  dio: ^5.4.1

  # UI/UX
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  lottie: ^3.1.2

  # File & Sharing
  pdf: ^3.10.8
  path_provider: ^2.1.2
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  # ADDED: Package for generating launcher icons
  flutter_launcher_icons: ^0.13.1

# ADDED: Configuration for the launcher icons package
flutter_launcher_icons:
  # This section configures the package for both Android and iOS
  android: "launcher_icon"
  ios: true
  # IMPORTANT: This is the path to the icon you added in Step 1
  image_path: "assets/icon/app_icon.png"
  # Ensures the icon works with modern Android versions' adaptive icons
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  
  # To add assets to your application, uncomment the following lines.
  assets:
    - assets/icon/